### ISSUE TITLE
Unexpected results when multiple processes use the same connection

### ISSUE THREAD

**Issue by schleyfox** [cstar/erldis#1]
Running the test: http://gist.github.com/395747

This issue has been cropping up in production for me as of late.  I use BERTRPC to handle some tasks in erlang.  A redis connection through erldis is used to give access to data.  BERTRPC works by spinning off a process on every RPC request it gets.  I would like to avoid the overhead and risk of failure (connection limits, etc.) associated with spawning a new redis connection every time a new process is created in erlang.  When multiple processes are using the connection simultaneously this sort of error crops up.

**Comment by schleyfox** [comment]
also assuming that processes sharing a connection is moderately expected behavior from comments like:

```
% japerk: do an erlang application with supervisor for client so that there
% is only one connection. Otherwise was getting issues with gen_tcp hanging
% on connect, even with a Timeout given.
-module(erldis_app).
```

in the source

**Comment by cstar** [comment]
I recommend you use a pool of gen_servers managing erldis connections within on OTP supervision tree. 

I have "corrected" your code adding a process in between your clients and erldis: http://gist.github.com/395823

The gen_server in charge of the socket to redis is async. It might be possible that some results are not properly reordered before besing sent back.

Also I have messaged Jacob Perkins, the erldis maintainer on bitbucket.

**Comment by schleyfox** [comment]
Yeah, I figured that would be a good solution.  My investigation of the issue shows that the commands are hitting redis well formed and without incident.  The specifics of the way it fails seems to show that results are being generated correctly, but erldis is incorrectly grouping multi-bulk replies (only reading/returning one or two of the elements of the result).  I think I shall try debugging this a bit further to make sure that the expected results are coming over the wire and investigate why things are not necessarily behaving as expected.

**Comment by schleyfox** [comment]
Ok, I'm wrapping up final tests of the solution and then cleaning up my code, but I found the issue.  Basically when a command is received it resets the State#redis.remaining count to 1 even if the remaining count is trying to piece together a multi bulk reply.  The solution is to only set the remaining count to 1 if the current remaining count is 0.  

Making this change caused my trivial test case to pass no problem.  I'm currently testing it in the context of how I'm using it in production.  I'm pumping a couple hundred thousand requests spawned over BERTRPC through it as fast as possible.  It seems to be working.

**Comment by cstar** [comment]
Great job!
Patch integrated : 63bda03b5832a5a8d2c2c916b427f9bb3be86733
